[versions]
annotations = "23.0.0"

# mongo distributions
mongo-driver = "4.4.1"

# jedis distributions
jedis = "4.1.1"

# spigot distributions
spigot = "1.8.8-R0.1-SNAPSHOT"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

# mongo distributions
mongo-driver = { module = "org.mongodb:mongodb-driver-sync", name = "mongo-driver", version.ref = "mongo-driver" }

# jedis distributions
jedis = { group = "redis.clients", name = "jedis", version.ref = "jedis" }

# spigon distributions
spigot = { module = "org.spigotmc:spigot-api", name = "spigot", version.ref = "spigot" }